# Generated by Django 3.2.8 on 2022-01-03 07:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20211209_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('uploaded_on', models.DateField(default=datetime.datetime(2022, 1, 3, 7, 26, 36, 939442, tzinfo=utc))),
                ('album_logo', models.FileField(upload_to=network.models.user_directory_path)),
                ('album_genre', models.CharField(max_length=30)),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=40)),
                ('song_file', models.FileField(upload_to=network.models.user_directory_path_song)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='network.album')),
            ],
        ),
    ]
